### ISSUE TITLE
Update landscape to reflect reality of the Foundation

### ISSUE THREAD

**Issue by bnb** [openjs-foundation/openjsf-landscape#12]
Despite Electron and AMP having moved out of incubation, it seems that their status has not been maintained in this repository.

**Comment by dankohn** [comment]
Do you want a hand fixing? It's a simple change to https://github.com/openjs-foundation/openjsf-landscape/blob/master/landscape.yml.

**Comment by bnb** [comment]
I'm not particularly interested in helping maintain this project, but if it is going to exist as a representation of the Foundation I do want to ensure I log issues when I encounter them.
